name: Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    
jobs:
  deno-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: denoland/setup-deno@v2
      with:
        deno-version: v2.0.3
    - run: deno test -A
      working-directory: ./examples/deno
      env:
        API_AUTHORIZATION: ${{ secrets.API_AUTHORIZATION }}
        DEPLOY_HOST: ${{ vars.DEPLOY_HOST }}

  node-jest:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20.16.0
    - run: npm i
      working-directory: ./examples/nodejs-jest
    - run: npm test
      working-directory: ./examples/nodejs-jest
      env:
        API_AUTHORIZATION: ${{ secrets.API_AUTHORIZATION }}
        DEPLOY_HOST: ${{ vars.DEPLOY_HOST }}
